base_image: ghcr.io/catthehacker/ubuntu:act-latest
base_image_distro: Ubuntu
base_image_description: Default runner image from act (act runs GitHub Actions locally)
os_installer: distro/debian/install.sh
test_suite: default
