name: Lint and Validate
run-name: Lint and validate (${{ github.ref_name }})

"on":
  workflow_call: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    name: Lint for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Ensure workflow actions use immutable refs
        uses: joshjohanning/ensure-immutable-actions@28e5544cb61fef95d00ee312614a29c8e3a68a19 # v2.5.4

      - name: "Test: Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.x"

      - name: "Test: Install shellcheck"
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: "Test: Remove Python yq and keep using Go yq"
        run: |
          python -m pip uninstall -y yq

      - name: "Test: Install lint deps"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: "Test: Run scripts/lint.sh"
        run: |
          chmod +x scripts/*.sh
          scripts/lint.sh
